title: Jingyang's Webpage
page-top-title: Jingyang (Edmond) Feng
top-section-bg-text: Be what you wanna be
home-subtitle: Jingyang&ensp;|&ensp;镜雪
copyright-text: '&copy; Jingyang 2025. All Rights Reserved.'
